#!/bin/csh

#=========================================================================#
#    Runs dataview on any selected field in the evolution subdirectory
#=========================================================================#

set n=$#argv

if ($n == 0) then
   echo
   echo '  Usage:   dv <field> <options>'
   echo
   echo '  Examples:'
   echo
   echo '  dv zz'
   echo '  dv zz -mod'
   echo '  dv zz -mod -cmap seismic'
   echo '  dv zz -lims -0.001 0.001'
   echo '  dv zz -notitle -cb'
   echo
   echo '  (For all options, just type "dataview")'
   echo
   exit (-1)
else
   set field=$1
endif

# Get resolution in latitude and longitude:
set ny = `grep "ng=" src/parameters.f90 | awk -F= '{print $(NF-1)}' | awk -F, '{print $1}'`
@ nx = ( 2 * $ny )

if ($n != 1) then
   # Remove first element of argument list <field> to get <options>:
   shift
   dataview -ndim $nx $ny $field{.r4} $argv &
else
   dataview -ndim $nx $ny $field{.r4} &
endif
