!#########################################################################
!  Finds the balanced fields from the conditions delta_t=gamma_t=0
!  using data previously generated by caps.

!           Written 5/4/2018 by D G Dritschel @ St Andrews
!#########################################################################

program dgbal

 !Import spectral module:
use spectral

implicit none

 !Physical fields:
double precision:: qq(ng,ng),hh(ng,ng),dd(ng,ng),gg(ng,ng)
double precision:: uu(ng,ng),vv(ng,ng),zz(ng,ng),aa(ng,ng)
double precision:: htot(ng,ng),wkp(ng,ng),wkq(ng,ng)
double precision:: hhpre(ng,ng),uupre(ng,ng),vvpre(ng,ng)

 !Spectral fields:
double precision:: ds(ng,ng),gs(ng,ng)
double precision:: wka(ng,ng),wkb(ng,ng),wkc(ng,ng),wkd(ng,ng),wke(ng,ng)

 !Other constants:
double precision,parameter:: tole=1.d-10
 !tole: relative energy norm error in successive iterates when finding
 !      hh, uu & vv from qq, dd & gg.  The energy error is computed from 
 !      <(u-u0)^2+(v-v0)^2+c^2*(h-h0)^2>/<u^2+v^2+c^2*h^2>
 !      where <:> means a domain average and (u0,v0,h0) is the previous
 !      guess for (u,v,h).
double precision:: qadd,qbar,fqbar,uio,vio
double precision:: dhrms,durms,enorm
double precision:: eu
real:: tr4,qqr4(ng,ng)
integer:: loop,iread

!----------------------------------------------------------------------
 !Initialise inversion constants and arrays:
call init_spectral

 !Open input data files:
open(31,file='qq.r4',form='unformatted',access='direct', &
                 & status='old',recl=nbytes)
open(32,file='dd.r4',form='unformatted',access='direct', &
                 & status='old',recl=nbytes)
open(33,file='gg.r4',form='unformatted',access='direct', &
                 & status='old',recl=nbytes)
open(34,file='hh.r4',form='unformatted',access='direct', &
                 & status='old',recl=nbytes)
open(35,file='zz.r4',form='unformatted',access='direct', &
                 & status='old',recl=nbytes)

 !Open output data files:
open(42,file='bdd.r4',form='unformatted',access='direct', &
                 & status='replace',recl=nbytes)
open(43,file='bgg.r4',form='unformatted',access='direct', &
                 & status='replace',recl=nbytes)
open(44,file='bhh.r4',form='unformatted',access='direct', &
                 & status='replace',recl=nbytes)
open(45,file='bzz.r4',form='unformatted',access='direct', &
                 & status='replace',recl=nbytes)
open(46,file='buu.r4',form='unformatted',access='direct', &
                 & status='replace',recl=nbytes)
open(47,file='bvv.r4',form='unformatted',access='direct', &
                 & status='replace',recl=nbytes)

open(51,file='bene.asc',status='replace')

!>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 !Read data and process:
loop=0
do
  loop=loop+1
  iread=0
  read(31,rec=loop,iostat=iread) tr4,qqr4
  if (iread .ne. 0) exit 
  qq=dble(qqr4)

  read(32,rec=loop,iostat=iread) tr4,qqr4
  dd=dble(qqr4)
  read(33,rec=loop,iostat=iread) tr4,qqr4
  gg=dble(qqr4)
  read(34,rec=loop,iostat=iread) tr4,qqr4
  hh=dble(qqr4)
  read(35,rec=loop,iostat=iread) tr4,qqr4
  zz=dble(qqr4)

  write(*,'(a,f9.2)') ' *** Processing t = ',tr4

  !-----------------------------------------------------------------
  !Obtain velocity field from dd & zz:
  aa=dd
  call ptospc(ng,ng,aa,ds,xfactors,yfactors,xtrig,ytrig)
  wke=rlap*ds
  call xderiv(ng,ng,hrkx,wke,wka)
  call yderiv(ng,ng,hrky,wke,wkb)

  aa=zz
  call ptospc(ng,ng,aa,wke,xfactors,yfactors,xtrig,ytrig)
  wke=rlap*wke
  call xderiv(ng,ng,hrkx,wke,wkc)
  call yderiv(ng,ng,hrky,wke,wkd)

  wka=wka-wkd
  wkb=wkb+wkc
  call spctop(ng,ng,wka,uu,xfactors,yfactors,xtrig,ytrig)
  call spctop(ng,ng,wkb,vv,xfactors,yfactors,xtrig,ytrig)

  !Add mean flow (uio,vio):
  uio=-sum(hh*uu)*dsumi
  vio=-sum(hh*vv)*dsumi
  uu=uu+uio
  vv=vv+vio

  !-----------------------------------------------------------------
  !Initialise arrays for iteration below:
  aa=gg
  call ptospc(ng,ng,aa,gs,xfactors,yfactors,xtrig,ytrig)

  !-----------------------------------------------------------------
  !Iterate to find the balanced fields:
  hhpre=hh
  uupre=uu
  vvpre=vv

  !Energy norm error (must be > tole to start):
  enorm=f12
  do while (enorm .gt. tole)
    !Obtain balanced estimate for gamma (gg):
    call jacob(uu,vv,wkp)
    call ptospc(ng,ng,wkp,wkb,xfactors,yfactors,xtrig,ytrig)
    wkp=dd*uu
    wkq=dd*vv
    call divs(wkp,wkq,wka)
    gs=filt*(wka-two*wkb)
    wka=gs
    call spctop(ng,ng,wka,gg,xfactors,yfactors,xtrig,ytrig)

    !Obtain balanced estimate for delta (dd):
    wkp=hh*uu
    wkq=hh*vv
    call divs(wkp,wkq,wka)
    wkp=zz*uu
    wkq=zz*vv
    call divs(wkp,wkq,wkb)
    ds=helm*(cof*wkb-c2g2*wka)
    wka=ds
    call spctop(ng,ng,wka,dd,xfactors,yfactors,xtrig,ytrig)

    !Find height anomaly field (hh):
    htot=one+hh
    qadd=-dsumi*sum(qq*htot)
    qq=qq+qadd
    qbar=dsumi*sum(qq)
    wkp=cof*(qq+hh*(qq-qbar))-gg
    call ptospc(ng,ng,wkp,wkb,xfactors,yfactors,xtrig,ytrig)
    fqbar=cof*qbar
    wka=filt*wkb/(opak-fqbar)
    call spctop(ng,ng,wka,hh,xfactors,yfactors,xtrig,ytrig)
     !wkp: corrected de-aliased height field (to be hh below)
    htot=one+hh
     !Compute rms error in hh:
    dhrms=sum((hh-hhpre)**2)

    !Obtain relative vorticity field (zz):
    wkp=qq*htot
    qadd=-dsumi*sum(wkp)
    qq=qq+qadd
    zz=htot*(cof+qq)-cof

    !Obtain velocity field (uu,vv):
    call ptospc(ng,ng,zz,wkb,xfactors,yfactors,xtrig,ytrig)
    wka=rlap*wkb
    wkb=filt*wkb
    call spctop(ng,ng,wkb,zz,xfactors,yfactors,xtrig,ytrig)
    call xderiv(ng,ng,hrkx,wka,wkd)
    call yderiv(ng,ng,hrky,wka,wkb)
    wke=rlap*ds
    call xderiv(ng,ng,hrkx,wke,wka)
    call yderiv(ng,ng,hrky,wke,wkc)
    wkb=wka-wkb
    wkd=wkc+wkd
    call spctop(ng,ng,wkb,uu,xfactors,yfactors,xtrig,ytrig)
    call spctop(ng,ng,wkd,vv,xfactors,yfactors,xtrig,ytrig)

    !Add mean flow (uio,vio):
    uio=-sum(hh*uu)*dsumi
    vio=-sum(hh*vv)*dsumi
    uu=uu+uio
    vv=vv+vio
     !Compute rms error in uu & vv:
    durms=sum((uu-uupre)**2+(vv-vvpre)**2)

     !Compute overall error:
    enorm=sqrt((durms+csq*dhrms)/sum(uupre**2+vvpre**2+csq*hhpre**2+1.d-20))

    write(*,*) ' Relative energy error = ',enorm

    !Otherwise continue with another iteration:
    hhpre=hh
    uupre=uu
    vvpre=vv
  enddo

  !Compute total balanced energy:
  eu=f12*garea*(sum(htot*(uu**2+vv**2)+csq*hh**2))

  !-----------------------------------------------------------------
  !Write data:
  write(42,rec=loop) tr4,real(dd)
  write(43,rec=loop) tr4,real(gg)
  write(44,rec=loop) tr4,real(hh)
  write(45,rec=loop) tr4,real(zz)
  write(51,'(f9.2,1x,f16.9)') tr4,eu
enddo
!<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

 !Close files:
close(31)
close(32)
close(33)
close(34)
close(35)
close(42)
close(43)
close(44)
close(45)
close(51)
close(61)

write(*,*)
write(*,*) ' Balanced fields generated.'

 !End main program
end program
!=======================================================================
