#!/usr/bin/env python3

# This script reads the buoyancy field at all times from the output
# of a SQG simulation.

import numpy as np

print
q_in = input(' Resolution (default 256)? ')
ng = int(q_in or 256)
N = ng*ng

#-------------------------------------------------------
# Open and read buoyancy data file:
in_file = open('bb.r4','r')
raw_array = np.fromfile(in_file,dtype = np.float32)
in_file.close()

# Set up array to contain data at any selected time frame (integer):
bb = np.empty([ng,ng])

q_in = input(' Frame to select (default 0)? ')
frame = int(q_in or 256)

# Get data at selected time:
bb = raw_array[frame*(N+1)+1:(frame+1)*(N+1)].reshape(ng,ng)
