#!/bin/csh

#=========================================================================#
#   Job setup script for the dam-break initial condition
#=========================================================================#
set datagen = "dam-break"

# Defaults:
set xfrac=0.75
set wfrac=0.01
#==========================================================================

echo ' Enter the x location of the density transition zone'
echo -n ' as a fraction of the domain width (default' $xfrac'): '
set var=$<
if ($var != "") set xfrac=$var

echo ' Enter the width of the density transition zone also'
echo -n ' as a fraction of the domain width (default' $wfrac'): '
set var=$<
if ($var != "") set wfrac=$var

echo ' ' >> job_info
echo ' Dam fractional location in x:      ' $xfrac >> job_info
echo ' Dam fractional width:              ' $wfrac >> job_info

cat << /EOF > in_$datagen
$xfrac
$wfrac
/EOF

$datagen < in_$datagen > out_$datagen
