#!/bin/csh

#=========================================================================#
#       Job setup script for the strat conf class of f90 codes.
#=========================================================================#

echo
echo '--------------------------------------------------------'
echo '       The general closed domain stratified flow'
echo '          Combined Lagrangian Advection Method'
echo '--------------------------------------------------------'

# Specify code numerical method class:
set meth="ca"
# Specify code geometry:
set geom="strat"
# Specify model equation type:
set equa="conf"
# Specify main algorithm name:
set algo="caps"

#==========================================================================
# The following is totally generic!
set local_home=`homedir`
set hydradir=$local_home/$user/hydra/$meth/$geom/$equa

# Get output base directory:
set basedir=`workdir`
# Make the base data directory if it does not already exist:
if (!(-d $basedir)) mkdir $basedir
set basedir=$basedir/hydra
if (!(-d $basedir)) mkdir $basedir
set basedir=$basedir/$meth
if (!(-d $basedir)) mkdir $basedir
set basedir=$basedir/$geom
if (!(-d $basedir)) mkdir $basedir
set basedir=$basedir/$equa
if (!(-d $basedir)) mkdir $basedir
set basedir=$basedir/$algo
if (!(-d $basedir)) mkdir $basedir

set outdir=$basedir

# Assign source and binary directories:
set srcdir=$hydradir/$algo
set bindir=$hydradir/scripts

# Get the name of the computer to record in the job_info file below:
set host=`hostname | awk -F. '{print $(1)}'`

#==========================================================================
# generate a random number seed based on current time:
set second=`date +%-S`
set minute=`date +%-M`
set hour=`date +%-H`
set day=`date +%-d`
@ iseed = ( $second + ( 60 * ( $minute + 60 * ( $hour + ( 24 * $day ) ) ) ) )

# Create a temporary directory:
set tmpdir=$outdir/tmp{$iseed}
mkdir $tmpdir
cd $tmpdir

echo
echo ' *** Job will be built in the temporary directory '
echo $tmpdir

# Create a job information summary file:
touch job_info
echo ' Job created at                      ' `date` >> job_info
echo ' on                                  ' $host >> job_info
echo ' ' >> job_info

#==========================================================================
# Get the data generation routine to be used:
set dataopt="1"
echo
echo ' Choose one of the following flow initialisation methods:'
echo    ' (1) a dam-break, or'
echo -n ' (2) a vortex  -  (default' $dataopt')? '
set var=$<
if ($var != "") set dataopt=$var
echo

if ($dataopt == "1") then 
   set datagen = "dam-break"
else if ($dataopt == "2") then 
   set datagen = "vort"
else 
   echo ' Not a valid choice - exiting...'
   /bin/rm -r $tmpdir  
   exit(-1)
endif

# Set defaults for numerical parameters:
set nx = "400"      # Inversion grid resolution in x
set ny = "200"      # Inversion grid resolution in y
set ncontz="50"     # Number of contours used to represent vorticity
set ncontb="100"    # Number of contours used to represent buoyancy
set tgsave="0.5"    # Grid data save time increment
set tcsave="5.0"    # Contour data save time increment
set tsim="100.0"    # Total simulation time
set nnu="3"         # Hyperviscous power
set prediss="100.0" # Damping rate in highest waveno.

#==========================================================================
# Choose numerical parameters:
echo
echo -n ' Grid resolution in x (default' $nx')? '
set var=$<
if ($var != "") set nx=$var
echo ' Inversion grid resolution in x:     ' $nx >> job_info

echo -n ' Grid resolution in y (default' $ny')? '
set var=$<
if ($var != "") set ny=$var
echo ' Inversion grid resolution in y:     ' $ny >> job_info

#echo -n ' No. of Vorticity jumps to represent (default' $ncontz')? '
#set var=$<
#if ($var != "") set ncontz=$var
#echo ' Number of jumps to represent zz, ncontz:' $ncontz >> job_info

#echo -n ' No. of Buoyancy jumps to represent (default' $ncontb')? '
#set var=$<
#if ($var != "") set ncontb=$var
#echo ' Number of jumps to represent bb, ncontb:' $ncontb >> job_info

echo
echo -n ' Time interval between gridded data saves (default' $tgsave')? '
set var=$<
if ($var != "") set tgsave=$var
echo ' Time interval between data saves:   ' $tgsave >> job_info

echo -n ' Time interval between contour data saves (default' $tcsave')? '
set var=$<
if ($var != "") set tcsave=$var
echo ' Time interval between contour saves:' $tcsave >> job_info

echo -n ' Total simulation time (default' $tsim')? '
set var=$<
if ($var != "") set tsim=$var
echo ' Total simulation time:              ' $tsim >> job_info
echo ' ' >> job_info

#==========================================================================
# Create resolution.asc containing nx & ny for python script below:
cat << /EOF > resolution.asc
$nx
$ny
/EOF

#==========================================================================
# Make sure we use python3:
set path=(/opt/python/miniconda/bin /opt/python/miniconda $path)

# Run python script to set up the conformal domain and grid:
python $bindir/python_matlab.py

# Extract domain dimensions from output file (domdim.asc):
set dum = `head -1 domdim.asc`
set xmin=$dum[1]
set xmax=$dum[2]
set dum = `tail -1 domdim.asc`
set ymin=$dum[1]
set ymax=$dum[2]

#============================================================
# Build parameter file with cpp and make all codes:

# Put all these dimensions into the dimens file needed for compilation:
mkdir src
cd src
/bin/cp $srcdir/* .
/bin/cp -r $hydradir/init .
/bin/cp -r $hydradir/post .

echo 
echo " Compiling source files....."
echo " -----------------------------------------------------------------------"

# Use C pre-processor to put chosen parameters $copts into parameters.f90
set copts="-DN_X=$nx -DN_Y=$ny -DN_CONTZ=$ncontz -DN_CONTB=$ncontb -DT_SIM={$tsim}d0 -DT_GSAVE={$tgsave}d0 -DT_CSAVE={$tcsave}d0 -DX_MIN={$xmin} -DX_MAX={$xmax} -DY_MIN={$ymin} -DY_MAX={$ymax} -DN_NU={$nnu} -DPRE_DISS={$prediss}d0"
precomp $copts parameters.f90

# Compile all codes and move sources to sub-directory:
make $algo setup $datagen proxy_post_all install clean

cd ..
echo " -----------------------------------------------------------------------"
echo 

#============================================================
# Execute the data generation script:
$bindir/$datagen

# Copy useful scripts to job directory:
/bin/cp $bindir/spec_view.py .
/bin/cp $bindir/eneplt.py .
/bin/cp $bindir/topoview .

#==========================================================================
# Create a directory named after the data generation script:
cd ..
if (!(-d $datagen)) mkdir $datagen
cd $datagen

# Set the job directory name (will be appended by 001, 002 etc...):
set basejobdir=nx{$nx}ny{$ny}
echo
echo -n ' Job directory name (default '{$basejobdir}')? '
set var=$<
if ($var != "") set basejobdir=$var

# work out the last run which has been performed:
# First make a bogus empty directory so this works!
mkdir {$basejobdir}r000
set last_run = `/bin/ls -d {$basejobdir}r??? | tail -c 4 | head -c 3`
rmdir {$basejobdir}r000

@ next_run = ( $last_run + 1 )
@ p1 = ( $next_run / 100 )
@ jr = ( $next_run - ( 100 * $p1 ) )
@ p2 = ( $jr / 10 )
@ p3 = ( $jr - ( 10 * $p2 ) )
set pind={$p1}{$p2}{$p3}

set jobdir={$basejobdir}r{$pind}

#=============================================================
# Lastly move all data to desired job directory:

# Move temporary directory to job directory:
mv $tmpdir $jobdir
cd $jobdir
set datadir=`pwd`

echo ' ' >> job_info
echo ' Job directory:' >> job_info
echo $datadir >> job_info

echo ' To set the job running, type'
echo cd $datadir
echo bat log caps
echo
