#!/usr/bin/env csh

#=========================================================================#
#   Job setup script for an initial condition consisting of a 
#   combination of several spherical harmonics.
#=========================================================================#

set datagen = "harmonic"

# Default input parameters:
set a1 = " 0.2"     # Amplitude of Y_1^1
set a2 = "-0.5"     # Amplitude of Y_2^1
set a3 = " 0.3"     # Amplitude of Y_3^3
set p2 = "30.0"     # Phase of Y_2^1 --- see below for use.
set p3 = "108.0"    # Phase of Y_3^3 --- see below for use.
#=========================================================================#

echo ' We set up a PV anomaly q consisting of the superposition of '
echo ' three spherical harmonics; Y_1^1, Y_2^1 and Y_3^3, specifically'
echo ' q = A_1*Re(Y_1^1)+A_2*Re(Y_2^1*exp(2i*p_2))+A_3*Re(Y_3^3*exp(3i*p_3))'

echo
echo -n ' Enter A_1 (default' $a1'): '
set var=$<
if ($var != "") set a1=$var
echo -n ' Enter A_2 (default' $a2'): '
set var=$<
if ($var != "") set a2=$var
echo -n ' Enter A_3 (default' $a3'): '
set var=$<
if ($var != "") set a3=$var
echo
echo -n ' Enter p_2 in degrees (default' $p2'): '
set var=$<
if ($var != "") set p2=$var
echo -n ' Enter p_3 in degrees (default' $p3'): '
set var=$<
if ($var != "") set p3=$var

echo ' ' >> job_info


echo ' Y_1^1 spherical harmonic amplitude   ' $a1 >> job_info
echo ' Y_2^1 spherical harmonic amplitude   ' $a2 >> job_info
echo ' Y_3^3 spherical harmonic amplitude   ' $a3 >> job_info
echo ' Y_2_1 spherical harmonic phase shift ' $p2 >> job_info
echo ' Y_3_3 spherical harmonic phase shift ' $p3 >> job_info

cat << /EOF > in_$datagen
$a1 $a2 $a3
$p2 $p3
/EOF

$datagen < in_$datagen > out_$datagen
