#!/bin/csh

#=========================================================================#
#   Job setup script for the random initial PV anomaly case
#=========================================================================#
set datagen = "randompv"

# Default input parameters:
set eps = "1.0"   # rms amplitude of PV anomaly relative to f_pole
#=========================================================================#

echo ' We consider a planet of radius 1 rotating with a period of one "day".'
echo
echo ' We start with a random PV anomaly field, with a rms value equal to'
echo ' f_pole*eps.'
echo -n ' Enter eps (default' $eps'): '
set var=$<
if ($var != "") set eps=$var

cat << /EOF > in_$datagen
$eps
/EOF

$datagen < in_$datagen > out_$datagen

echo ' Initial rms PV anomaly/f_pole:      ' $eps >> job_info
