#!/bin/csh

#=========================================================================#
#   Job setup script for the Random forcing case
#=========================================================================#
set datagen = "rest-state"

# Set fixed constants:
set pi=3.14159265358979
set twopi=`echo "scale=10; 2 * $pi" | bc -l`


$datagen 
