#!/usr/bin/env csh

# Assigns the user's home disk where all source codes and scripts are kept

set host = `hostname | awk -F. '{print $(1)}'`

if ( ($host == "davidd-latitude-5430") || ($host == "taybeh") ) then
# laptop at home:

   echo '/home'

else if ($host =~ "login-[1-4]") then

   echo $HOME

else
# all other machines:

   echo '/user'

endif
