#!/bin/csh

# Assigns a disk where the job output will go

set host = `hostname | awk -F. '{print $(1)}'`

if ( $host == "davidd-latitude-5430" ) then
# laptop at home:

   echo /home/dgd/data

else if ( ($host == cyclone) || ($host == vortex) || ($host == tornado) || ($host == fortran1) ) then

   echo /scratch/$user

else if ( ($host == taybeh) || ($host == login-1) || ($host == login-2) || ($host == login-3) || ($host == login-4) ) then

   echo $HOME/output-hydra

else
# all other machines:

   echo /local_raid/$user

endif
